name = "teaminox-platform"
pages_build_output_dir = "dist"
compatibility_date = "2026-05-18"
account_id = "d250c28da80a5b0a5f0a4bbd9d4b0e18"

[[d1_databases]]
binding = "ZRL_DB"
database_name = "team_inox_prod_v3"
database_id = "c61ac3e9-4a68-4834-9f6e-297a7437451f"

[[d1_databases]]
binding = "ZRL_DB_V2"
database_name = "team_inox_prod_v2"
database_id = "5bc66f8c-227f-4492-9361-d32f2a07b53a"

[ai]
binding = "AI"
