name = "inoxteam-pages-functions"
compatibility_date = "2024-05-18"

# ❌ RIMUOVI completamente questa riga
# main = false

# Configurazione D1
[[d1_databases]]
binding = "DB"
database_name = "inox_auth_db"
database_id = "c45289cd-c758-4a9b-85c8-3e06713df1e4"

[dev]
port = 8787